### ISSUE TITLE
Broken outgoingRelations in redirect asset inferred as HTML

### ISSUE THREAD

**Issue by Munter** [assetgraph/assetgraph#1060]
I have this HTTP response:

```
$ curl -i https://webpack.js.org/concepts
HTTP/2 301
date: Wed, 30 Oct 2019 09:30:20 GMT
content-type: text/html
content-length: 162
set-cookie: __cfduid=d1b1cfccb28bdcb716703104ce1880cba1572427820; expires=Thu, 29-Oct-20 09:30:20 GMT; path=/; domain=.js.org; HttpOnly
location: http://webpack.js.org/concepts/
access-control-allow-origin: *
expires: Wed, 30 Oct 2019 09:40:20 GMT
cache-control: max-age=600
x-proxy-cache: MISS
x-github-request-id: 195E:4331:7B403:A1CC4:5DB9582A
accept-ranges: bytes
via: 1.1 varnish
age: 0
x-served-by: cache-cph20640-CPH
x-cache: MISS
x-cache-hits: 0
x-timer: S1572427820.101153,VS0,VE101
vary: Accept-Encoding
x-fastly-request-id: 170dfd7c37d344e8110ec8d75667d982065c1db6
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 52dc5eb38dddd8ad-CPH

<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

The Asset will be marked as `isRedirect: true`, but also inferred as `HTML`. When I access the assets `.outgoingRelations`, this error is thrown:

```
Error: Text._getTextFromRawSrc(): No _rawSrc property found: https://webpack.js.org/concepts
    at Html._getTextFromRawSrc (/Users/munter/git/hyperlink/node_modules/assetgraph/lib/assets/Text.js:216:13)
    at Html.get parseTree [as parseTree] (/Users/munter/git/hyperlink/node_modules/assetgraph/lib/assets/Html.js:183:21)
    at Html.findOutgoingRelationsInParseTree (/Users/munter/git/hyperlink/node_modules/assetgraph/lib/assets/Html.js:344:12)
    at Html.get outgoingRelations [as outgoingRelations] (/Users/munter/git/hyperlink/node_modules/assetgraph/lib/assets/Asset.js:1058:38)
    at hyperlink (/Users/munter/git/hyperlink/lib/index.js:676:40)
    at <anonymous>
```

**Comment by papandreou** [comment]
Well, it is both! It's an HTML asset with a `Content-Type` of `text/html` and it has a `Location` header that points somewhere else. So we're also providing the 301 page as an actual asset in the graph, making sure that it also has the `HttpRedirect` relation among its outgoing relations. It feels a bit awkward, and we really should make it easier to work with both fs and http redirects, but I haven't been able to come up with a better idea.

There could still be a bug, though. Could you paste the code snippet that fails like that? The error you're seeing indicates that you haven't loaded the redirect asset?

**Comment by Munter** [comment]
I added a broken test case in hyperlink to illustrate the problem: https://github.com/Munter/hyperlink/pull/166

**Comment by papandreou** [comment]
It references `testdata/htmlInRedirect`, which doesn't exist. Did you forget to include that?

**Comment by Munter** [comment]
Doh. Yes

**Comment by papandreou** [comment]
Pushed a fix

**Comment by papandreou** [comment]
Oh, that wasn't actually enough. I've pushed some more fixes so that the test actually passes now :)

**Comment by papandreou** [comment]
Fixed now.
