### ISSUE TITLE
Crash inside escodegen when minifying JavaScript class statement.

### ISSUE THREAD

**Issue by kevincox** [assetgraph/assetgraph#1303]
```js
// www/foo.js

export class Foo {
	foo = true;
}
```

```js
// build.js
(async ()=>{
	let AssetGraph = require("assetgraph");

	let assetGraph = new AssetGraph({ root: "www/" });

	await assetGraph.loadAssets("*.js"); // Load all Html assets in the root dir

	for (let js of assetGraph.findAssets({type: "JavaScript"})) {
		js.minify();
	}

	await assetGraph.writeAssetsToDisc({ protocol: "file:" }, "out/");
})()
```

Result:

```
TypeError: this[type] is not a function
    at CodeGenerator.generateExpression (/home/kevincox/Downloads/node_modules/escodegen/escodegen.js:2516:28)
    at /home/kevincox/Downloads/node_modules/escodegen/escodegen.js:1133:38
    at withIndent (/home/kevincox/Downloads/node_modules/escodegen/escodegen.js:581:9)
    at CodeGenerator.ClassBody (/home/kevincox/Downloads/node_modules/escodegen/escodegen.js:1128:13)
    at CodeGenerator.generateStatement (/home/kevincox/Downloads/node_modules/escodegen/escodegen.js:2529:33)
    at CodeGenerator.ClassDeclaration (/home/kevincox/Downloads/node_modules/escodegen/escodegen.js:1159:30)
    at CodeGenerator.generateStatement (/home/kevincox/Downloads/node_modules/escodegen/escodegen.js:2529:33)
    at CodeGenerator.ExportNamedDeclaration (/home/kevincox/Downloads/node_modules/escodegen/escodegen.js:1237:42)
    at CodeGenerator.generateStatement (/home/kevincox/Downloads/node_modules/escodegen/escodegen.js:2529:33)
    at CodeGenerator.Program (/home/kevincox/Downloads/node_modules/escodegen/escodegen.js:1718:43)
    at CodeGenerator.generateStatement (/home/kevincox/Downloads/node_modules/escodegen/escodegen.js:2529:33)
    at generateInternal (/home/kevincox/Downloads/node_modules/escodegen/escodegen.js:2550:28)
    at Object.generate (/home/kevincox/Downloads/node_modules/escodegen/escodegen.js:2618:18)
    at get text [as text] (/home/kevincox/Downloads/node_modules/assetgraph/lib/assets/JavaScript.js:81:21)
    at get rawSrc [as rawSrc] (/home/kevincox/Downloads/node_modules/assetgraph/lib/assets/Text.js:82:30)
    at Promise.map.concurrency (/home/kevincox/Downloads/node_modules/assetgraph/lib/transforms/writeAssetsToDisc.js:60:19)
    at tryCatcher (/home/kevincox/Downloads/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/home/kevincox/Downloads/node_modules/bluebird/js/release/map.js:68:38)
    at PromiseArray._iterate (/home/kevincox/Downloads/node_modules/bluebird/js/release/promise_array.js:115:31)
    at MappingPromiseArray.init (/home/kevincox/Downloads/node_modules/bluebird/js/release/promise_array.js:79:10)
    at MappingPromiseArray._asyncInit (/home/kevincox/Downloads/node_modules/bluebird/js/release/map.js:37:10)
    at _drainQueueStep (/home/kevincox/Downloads/node_modules/bluebird/js/release/async.js:97:12)
```

# Versions

assetgraph: 7.12.0
node: 20.11.1

[package-lock.json](https://github.com/assetgraph/assetgraph/files/14872136/package-lock.json)

**Comment by kevincox** [comment]
Inserting a print statement into escodegen I see that the unknown type is `PropertyDefinition`.

**Comment by kevincox** [comment]
<pre><span style="background-color:#171421"><font color="#8B8A88">%</font></span><span style="background-color:#171421"><b> rg -w PropertyDefinition node_modules</b></span>
<font color="#A347BA">node_modules/acorn/dist/acorn.d.mts</font>
<font color="#26A269">375</font>:  body: Array&lt;MethodDefinition | <font color="#C01C28"><b>PropertyDefinition</b></font> | StaticBlock&gt;
<font color="#26A269">479</font>:export interface <font color="#C01C28"><b>PropertyDefinition</b></font> extends Node {
<font color="#26A269">480</font>:  type: &quot;<font color="#C01C28"><b>PropertyDefinition</b></font>&quot;
<font color="#26A269">565</font>:export type AnyNode = Statement | Expression | Declaration | ModuleDeclaration | Literal | Program | SwitchCase | CatchClause | Property | Super | SpreadElement | TemplateElement | AssignmentProperty | ObjectPattern | ArrayPattern | RestElement | AssignmentPattern | ClassBody | MethodDefinition | MetaProperty | ImportSpecifier | ImportDefaultSpecifier | ImportNamespaceSpecifier | ExportSpecifier | AnonymousFunctionDeclaration | AnonymousClassDeclaration | <font color="#C01C28"><b>PropertyDefinition</b></font> | PrivateIdentifier | StaticBlock

<font color="#A347BA">node_modules/acorn/dist/acorn.d.ts</font>
<font color="#26A269">375</font>:  body: Array&lt;MethodDefinition | <font color="#C01C28"><b>PropertyDefinition</b></font> | StaticBlock&gt;
<font color="#26A269">479</font>:export interface <font color="#C01C28"><b>PropertyDefinition</b></font> extends Node {
<font color="#26A269">480</font>:  type: &quot;<font color="#C01C28"><b>PropertyDefinition</b></font>&quot;
<font color="#26A269">565</font>:export type AnyNode = Statement | Expression | Declaration | ModuleDeclaration | Literal | Program | SwitchCase | CatchClause | Property | Super | SpreadElement | TemplateElement | AssignmentProperty | ObjectPattern | ArrayPattern | RestElement | AssignmentPattern | ClassBody | MethodDefinition | MetaProperty | ImportSpecifier | ImportDefaultSpecifier | ImportNamespaceSpecifier | ExportSpecifier | AnonymousFunctionDeclaration | AnonymousClassDeclaration | <font color="#C01C28"><b>PropertyDefinition</b></font> | PrivateIdentifier | StaticBlock

<font color="#A347BA">node_modules/acorn/dist/acorn.js</font>
<font color="#26A269">1565</font>:    return this.finishNode(field, &quot;<font color="#C01C28"><b>PropertyDefinition</b></font>&quot;)

<font color="#A347BA">node_modules/acorn/dist/acorn.mjs</font>
<font color="#26A269">1559</font>:  return this.finishNode(field, &quot;<font color="#C01C28"><b>PropertyDefinition</b></font>&quot;)

<font color="#A347BA">node_modules/terser/lib/mozilla-ast.js</font>
<font color="#26A269">434</font>:        <font color="#C01C28"><b>PropertyDefinition</b></font>: function(M) {
<font color="#26A269">448</font>:                    throw new Error(&quot;Non-Identifier key in <font color="#C01C28"><b>PropertyDefinition</b></font>&quot;);
<font color="#26A269">720</font>:                        : p.type == &quot;<font color="#C01C28"><b>PropertyDefinition</b></font>&quot; || p.type === &quot;FieldDefinition&quot; ? (p.key === M &amp;&amp; p.computed || p.value === M ? AST_SymbolRef : AST_SymbolClassProperty)
<font color="#26A269">1606</font>:                type: &quot;<font color="#C01C28"><b>PropertyDefinition</b></font>&quot;,
<font color="#26A269">1618</font>:                type: &quot;<font color="#C01C28"><b>PropertyDefinition</b></font>&quot;,

<font color="#A347BA">node_modules/terser/dist/bundle.min.js</font>
<font color="#26A269">7410</font>:        <font color="#C01C28"><b>PropertyDefinition</b></font>: function(M) {
<font color="#26A269">7424</font>:                    throw new Error(&quot;Non-Identifier key in <font color="#C01C28"><b>PropertyDefinition</b></font>&quot;);
<font color="#26A269">7696</font>:                        : p.type == &quot;<font color="#C01C28"><b>PropertyDefinition</b></font>&quot; || p.type === &quot;FieldDefinition&quot; ? (p.key === M &amp;&amp; p.computed || p.value === M ? AST_SymbolRef : AST_SymbolClassProperty)
<font color="#26A269">8582</font>:                type: &quot;<font color="#C01C28"><b>PropertyDefinition</b></font>&quot;,
<font color="#26A269">8594</font>:                type: &quot;<font color="#C01C28"><b>PropertyDefinition</b></font>&quot;,

<font color="#A347BA">node_modules/uglify-js/lib/mozilla-ast.js</font>
<font color="#26A269">176</font>:        <font color="#C01C28"><b>PropertyDefinition</b></font>: function(M) {
<font color="#26A269">741</font>:            type: &quot;<font color="#C01C28"><b>PropertyDefinition</b></font>&quot;,

<font color="#A347BA">node_modules/estraverse/estraverse.js</font>
<font color="#26A269">130</font>:        <font color="#C01C28"><b>PropertyDefinition</b></font>: &apos;<font color="#C01C28"><b>PropertyDefinition</b></font>&apos;,
<font color="#26A269">208</font>:        <font color="#C01C28"><b>PropertyDefinition</b></font>: [&apos;key&apos;, &apos;value&apos;],
</pre>

**Comment by kevincox** [comment]
It seems like the latest `escodegen` doesn't support this.

I see https://github.com/estools/escodegen/pull/438. However it creates a handler for `FieldDefinition` not `PropertyDefinition`.

I see https://github.com/estools/escodegen/issues/443 which creates `PropertyDefinition` however talks about state class fields. So unless the field is being promoted to static by Terser I'm not sure which is right without more research.

**Comment by papandreou** [comment]
@kevincox, would you be up for contributing a fix to escodegen?

**Comment by kevincox** [comment]
Unlikely to happen soon. But maybe at some point.

**Comment by papandreou** [comment]
In any case, that's where it has to be implemented.

A good starting point would be to look at the [estree spec for `PropertyDefinition`](https://github.com/estree/estree/blob/master/es2022.md#propertydefinition) and working up a test case for escodegen.

**Comment by papandreou** [comment]
I guess we could also try to replace escodegen with another module, such as [astring](https://github.com/davidbonnet/astring). That's just a bit more complicated, as we've exposed some of escodegen's flags in different places.

**Comment by kevincox** [comment]
I ended up implementing it: https://github.com/estools/escodegen/pull/465

**Comment by papandreou** [comment]
Excellent! :muscle:
