### ISSUE TITLE
TypeError while parsing internal requirejs tests

### ISSUE THREAD

**Issue by passy** [assetgraph/assetgraph#157]
`assetgraph-builer` dies on a TypeError while evaluating what seems to be an internal test case from requireJs.

The text of that file is

``` js
require({
  baseUrl: './',
  paths: {
    system: '../system',
    test: '../test'
  }
}, ['program']);
```

It raises the following error:

``` js
TypeError: loadAssets transform: Cannot call method 'forEach' of undefined
    at extractRequireJsConfig (/home/pascal/Projects/javascript/ctlmngr/node_modules/grunt-reduce/node_modules/assetgraph-builder/node_modules/assetgraph/lib/transforms/registerRequireJsConfig.js:102:3
9)
    at Object.visit (/home/pascal/Projects/javascript/ctlmngr/node_modules/grunt-reduce/node_modules/assetgraph-builder/node_modules/assetgraph/lib/transforms/registerRequireJsConfig.js:149:25)
    at Object.TreeWalker._visit (/home/pascal/Projects/javascript/ctlmngr/node_modules/grunt-reduce/node_modules/assetgraph-builder/node_modules/assetgraph/node_modules/uglify-js-papandreou/lib/ast.js:
928:24)
    at AST_Node.DEFNODE._walk (/home/pascal/Projects/javascript/ctlmngr/node_modules/grunt-reduce/node_modules/assetgraph-builder/node_modules/assetgraph/node_modules/uglify-js-papandreou/lib/ast.js:13
7:24)
    at /home/pascal/Projects/javascript/ctlmngr/node_modules/grunt-reduce/node_modules/assetgraph-builder/node_modules/assetgraph/node_modules/uglify-js-papandreou/lib/ast.js:148:14
    at Array.forEach (native)
    at walk_body (/home/pascal/Projects/javascript/ctlmngr/node_modules/grunt-reduce/node_modules/assetgraph-builder/node_modules/assetgraph/node_modules/uglify-js-papandreou/lib/ast.js:147:20)
    at AST_Node.<anonymous> (/home/pascal/Projects/javascript/ctlmngr/node_modules/grunt-reduce/node_modules/assetgraph-builder/node_modules/assetgraph/node_modules/uglify-js-papandreou/lib/ast.js:368:
13)
    at Object.TreeWalker._visit (/home/pascal/Projects/javascript/ctlmngr/node_modules/grunt-reduce/node_modules/assetgraph-builder/node_modules/assetgraph/node_modules/uglify-js-papandreou/lib/ast.js:
932:21)
    at AST_Node.DEFNODE._walk (/home/pascal/Projects/javascript/ctlmngr/node_modules/grunt-reduce/node_modules/assetgraph-builder/node_modules/assetgraph/node_modules/uglify-js-papandreou/lib/ast.js:36
3:24)
```

Running `assetgraph@1.6.2`, but master seems to be unmodified for the affected files:

```
├─┬ grunt-reduce@0.1.12
│ └─┬ assetgraph-builder@1.8.4
│   ├─┬ assetgraph@1.6.2
```

**Comment by papandreou** [comment]
This should no longer be a problem since the require.js support was rewritten to use the require.js optimizer.
